/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javatest;

import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rushil
 */
public class GUI extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public GUI() {
        initComponents();
        reloadTable();
        reloadModulesTable();
        reloadPresence();
    }
    
    public String hostDatabase = "127.0.0.1/java";
    public String username = "root";
    public String password = "tokina01";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void reloadPresence(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            String sql1 = "SELECT DISTINCT cohort FROM studenten ORDER BY 1;";
            pst = con.prepareStatement(sql1);
            rs = pst.executeQuery();
            cohortComboBox.removeAllItems();
            while(rs.next()){
                String name1 = rs.getString("cohort");
                cohortComboBox.addItem(name1);
            }
            String sql2 = "SELECT DISTINCT studie_richting FROM studenten ORDER BY 1;";
            pst = con.prepareStatement(sql2);
            rs = pst.executeQuery();
            studrComboBox.removeAllItems();
            while(rs.next()){
                String name2 = rs.getString("studie_richting");
                studrComboBox.addItem(name2);
            }
            String sql3 = "SELECT DISTINCT module_code FROM modules ORDER BY 1;";
            pst = con.prepareStatement(sql3);
            rs = pst.executeQuery();
            moduleComboBox.removeAllItems();
            while(rs.next()){
                String name3 = rs.getString("module_code");
                moduleComboBox.addItem(name3);
            }
            DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
            int rowcount = dtm.getRowCount();
            if (rowcount > 0){
                for (int i = rowcount - 1; i>=0; i--) {
                    dtm.removeRow(i);
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void reloadTable() {
        try{
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            String sql = "SELECT stud_nr AS 'Stud. Nr.', f_name AS 'Voornaam', l_name AS 'Achternaam', cohort as 'Cohort', studie_richting AS 'Studie Richting' FROM studenten";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setEnabled(false);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void reloadModulesTable() {
        try{
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            String sql = "SELECT id AS ID, module_code AS 'Module Code', module_name AS 'Module Name' FROM modules;";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            jTable2.setEnabled(false);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        studnr = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        cohort = new javax.swing.JTextField();
        studierichting = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        searchBar = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        modulesTable = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        moduleCodeField = new javax.swing.JTextField();
        moduleNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createModuleButton = new javax.swing.JButton();
        updateModuleButton = new javax.swing.JButton();
        deleteModuleButton = new javax.swing.JButton();
        moduleSearchButton = new javax.swing.JButton();
        moduleSearch = new javax.swing.JTextField();
        moduleResetButton = new javax.swing.JButton();
        loadInButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        moduleIdField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cohortComboBox = new javax.swing.JComboBox<>();
        studrComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        loadPresenceButton = new javax.swing.JButton();
        resetPresenceButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        savePresenceButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        moduleComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Stud. Nr");

        jLabel2.setText("Studierichting");

        jLabel3.setText("Voornaam:");

        jLabel4.setText("Cohort");

        jLabel5.setText("Achternaam");

        studnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studnrActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stud. Nr.", "Voornaam", "Achternaam", "Cohort", "Studierichting"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load In");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cohort, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studierichting, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studnr, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchBar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(studnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cohort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(studierichting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Studenten", jPanel2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Module Code", "Module"
            }
        ));
        modulesTable.setViewportView(jTable2);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Module Code:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Module Name:");

        createModuleButton.setText("Create");
        createModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createModuleButtonActionPerformed(evt);
            }
        });

        updateModuleButton.setText("Update");
        updateModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateModuleButtonActionPerformed(evt);
            }
        });

        deleteModuleButton.setText("Delete");
        deleteModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteModuleButtonActionPerformed(evt);
            }
        });

        moduleSearchButton.setText("Search");
        moduleSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleSearchButtonActionPerformed(evt);
            }
        });

        moduleResetButton.setText("Reset");
        moduleResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleResetButtonActionPerformed(evt);
            }
        });

        loadInButton.setText("Load In");
        loadInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadInButtonActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createModuleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 44, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(updateModuleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(moduleIdField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(moduleCodeField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(moduleNameField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(loadInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moduleResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modulesTable, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(moduleSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moduleSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moduleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moduleSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moduleIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(9, 9, 9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modulesTable, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moduleCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moduleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createModuleButton)
                            .addComponent(updateModuleButton)
                            .addComponent(deleteModuleButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moduleResetButton)
                            .addComponent(loadInButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Modules", jPanel3);

        cohortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        studrComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("COHORT:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Studie Richting:");

        loadPresenceButton.setText("Load Table");
        loadPresenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPresenceButtonActionPerformed(evt);
            }
        });

        resetPresenceButton.setText("Reset Table");
        resetPresenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPresenceButtonActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(13172), null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Stud. Nr.", "Voornaam", "Achternaam", "Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6", "Week 7", "Week 8"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable3);

        savePresenceButton.setText("Save");
        savePresenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePresenceButtonActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Module:");

        moduleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cohortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studrComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moduleComboBox, 0, 117, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadPresenceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetPresenceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(savePresenceButton)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cohortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studrComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(loadPresenceButton)
                    .addComponent(resetPresenceButton)
                    .addComponent(jLabel11)
                    .addComponent(moduleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePresenceButton)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Presentie", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studnrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // CREATE BUTTON
        try{
        String sql = "INSERT INTO `studenten`"
                +"(f_name, l_name, cohort, studie_richting) "
                +"VALUES (?,?,?,?)";
        con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
        pst = con.prepareStatement(sql);
        pst.setString(1, fname.getText());
        pst.setString(2, lname.getText());
        pst.setInt(3, Integer.parseInt(cohort.getText()));
        pst.setString(4, studierichting.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Success!");
        studnr.setText(null);
        fname.setText(null);
        lname.setText(null);
        cohort.setText(null);
        studierichting.setText(null);
        reloadTable();
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // DELETE BUTTON
        try {
            String sqldelete = "DELETE FROM studenten WHERE stud_nr=?";
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            pst = con.prepareStatement(sqldelete);
            pst.setString(1, studnr.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Success!");
            studnr.setText(null);
            fname.setText(null);
            lname.setText(null);
            cohort.setText(null);
            studierichting.setText(null);
            reloadTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // UPDATE BUTTON
        try {
            String sqlupdate = "UPDATE studenten SET f_name=?,l_name=?,cohort=?, studie_richting=? WHERE stud_nr=?";
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            pst = con.prepareStatement(sqlupdate);
            pst.setInt(5, Integer.parseInt(studnr.getText()));
            pst.setString(1, fname.getText());
            pst.setString(2, lname.getText());
            pst.setInt(3, Integer.parseInt(cohort.getText()));
            pst.setString(4, studierichting.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Success!");
            studnr.setText(null);
            fname.setText(null);
            lname.setText(null);
            cohort.setText(null);
            studierichting.setText(null);
            reloadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // SEARCH BUTTON
        try{
            String sqlsearch = "SELECT stud_nr AS 'Stud. Nr.', f_name AS 'Voornaam', l_name AS 'Achternaam', cohort as 'Cohort', studie_richting AS 'Studie Richting' FROM studenten WHERE stud_nr = ? OR f_name LIKE ? OR l_name LIKE ?";
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            pst = con.prepareStatement(sqlsearch);
            pst.setString(1, searchBar.getText());
            pst.setString(2, "%" + searchBar.getText() + "%");
            pst.setString(3, "%" + searchBar.getText() + "%");
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setEnabled(false);
            studnr.setText(null);
            fname.setText(null);
            lname.setText(null);
            cohort.setText(null);
            studierichting.setText(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // RESET BUTTON
        studnr.setText(null);
        fname.setText(null);
        lname.setText(null);
        cohort.setText(null);
        studierichting.setText(null);
        searchBar.setText(null);
        reloadTable();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // LOAD IN BUTTON
        try {
            int pk = Integer.parseInt(studnr.getText());
            String loadInQuery = "SELECT stud_nr AS 'Stud. Nr.', f_name AS 'Voornaam', l_name AS 'Achternaam', cohort as 'Cohort', studie_richting AS 'Studie Richting' FROM studenten WHERE stud_nr=?";
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            pst = con.prepareStatement(loadInQuery);
            pst.setInt(1, pk);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
//            System.out.println(columnCount);
            ArrayList<String> recordList = new ArrayList<>(columnCount);
            while (rs.next()){
                int i = 1;
                while (i <= columnCount){
                    recordList.add(rs.getString(i++));
                }
            }
            fname.setText(recordList.get(1));
            lname.setText(recordList.get(2));
            cohort.setText(recordList.get(3));
            studierichting.setText(recordList.get(4));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    private void moduleResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleResetButtonActionPerformed
        // RESET MODULE BUTTON
        reloadModulesTable();
        moduleIdField.setText(null);
        moduleCodeField.setText(null);
        moduleNameField.setText(null);
        moduleSearch.setText(null);
    }//GEN-LAST:event_moduleResetButtonActionPerformed

    private void createModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createModuleButtonActionPerformed
        // CREATE MODULE BUTTON
        try{
            String sql = "INSERT INTO `modules`"
                    +"(module_code, module_name) "
                    +"VALUES (?,?)";
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            pst = con.prepareStatement(sql);
            pst.setString(1, moduleCodeField.getText());
            pst.setString(2, moduleNameField.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Success!");
            moduleCodeField.setText(null);
            moduleNameField.setText(null);
            reloadModulesTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_createModuleButtonActionPerformed

    private void deleteModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteModuleButtonActionPerformed
        // DELETE MODULE BUTTON
        try {
            String sqldelete = "DELETE FROM modules WHERE id=?";
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            pst = con.prepareStatement(sqldelete);
            pst.setString(1, moduleIdField.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Success!");
            moduleIdField.setText(null);
            moduleCodeField.setText(null);
            moduleNameField.setText(null);
            reloadModulesTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteModuleButtonActionPerformed

    private void updateModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateModuleButtonActionPerformed
        // UPDATE MODULE BUTTON
        try {
            String sqlupdate = "UPDATE modules SET module_code=?,module_name=? WHERE id=?";
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            pst = con.prepareStatement(sqlupdate);
            pst.setString(3, moduleIdField.getText());
            pst.setString(1, moduleCodeField.getText());
            pst.setString(2, moduleNameField.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Success!");
            moduleIdField.setText(null);
            moduleCodeField.setText(null);
            moduleNameField.setText(null);
            reloadModulesTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_updateModuleButtonActionPerformed

    private void loadInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadInButtonActionPerformed
        // LOAD IN BUTTON
        try {
            int pk = Integer.parseInt(moduleIdField.getText());
            String loadInQuery = "SELECT id AS 'ID', module_code AS 'Module Code', module_name AS 'Module Name' FROM modules WHERE id=?";
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            pst = con.prepareStatement(loadInQuery);
            pst.setInt(1, pk);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
//            System.out.println(columnCount);
            ArrayList<String> recordList = new ArrayList<>(columnCount);
            while (rs.next()){
                int i = 1;
                while (i <= columnCount){
                    recordList.add(rs.getString(i++));
                }
            }
            moduleCodeField.setText(recordList.get(1));
            moduleNameField.setText(recordList.get(2));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loadInButtonActionPerformed

    private void moduleSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleSearchButtonActionPerformed
        // SEARCH BUTTON
        try{
            String sqlsearch = "SELECT id AS 'ID', module_code AS 'Module Code', module_name AS 'Module Name' FROM modules WHERE id = ? OR module_code LIKE ? OR module_name LIKE ?";
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            pst = con.prepareStatement(sqlsearch);
            pst.setString(1, moduleSearch.getText());
            pst.setString(2, "%" + moduleSearch.getText() + "%");
            pst.setString(3, "%" + moduleSearch.getText() + "%");
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            jTable2.setEnabled(false);
            moduleIdField.setText(null);
            moduleCodeField.setText(null);
            moduleNameField.setText(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_moduleSearchButtonActionPerformed

    private void savePresenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePresenceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savePresenceButtonActionPerformed

    private void resetPresenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPresenceButtonActionPerformed
        reloadPresence();
    }//GEN-LAST:event_resetPresenceButtonActionPerformed

    private void loadPresenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPresenceButtonActionPerformed
        try{
            String cohortCBB = String.valueOf(cohortComboBox.getSelectedItem());
            String studCBB = String.valueOf(studrComboBox.getSelectedItem());
            String presenceSQL = "SELECT stud_nr AS 'Stud. Nr.', f_name AS 'Voornaam', l_name AS 'Achternaam', week_1 AS 'Week 1', week_2 AS 'Week 2', week_3 AS 'Week 3', week_4 AS 'Week 4', week_5 AS 'Week 5', week_6 AS 'Week 6', week_7 AS 'Week 7', week_8 AS 'Week 8' FROM studenten s LEFT JOIN  presentie p ON s.stud_nr = p.stud_id WHERE s.cohort = ? AND s.studie_richting = ? ORDER BY s.l_name, s.f_name;";
            con = DriverManager.getConnection("jdbc:mysql://" + hostDatabase, username, password);
            pst = con.prepareStatement(presenceSQL);
            pst.setInt(1, Integer.parseInt(cohortCBB));
            pst.setString(2, studCBB);
            rs = pst.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_loadPresenceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cohort;
    private javax.swing.JComboBox<String> cohortComboBox;
    private javax.swing.JButton createModuleButton;
    private javax.swing.JButton deleteModuleButton;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField lname;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton loadInButton;
    private javax.swing.JButton loadPresenceButton;
    private javax.swing.JTextField moduleCodeField;
    private javax.swing.JComboBox<String> moduleComboBox;
    private javax.swing.JTextField moduleIdField;
    private javax.swing.JTextField moduleNameField;
    private javax.swing.JButton moduleResetButton;
    private javax.swing.JTextField moduleSearch;
    private javax.swing.JButton moduleSearchButton;
    private javax.swing.JScrollPane modulesTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetPresenceButton;
    private javax.swing.JButton savePresenceButton;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField studierichting;
    private javax.swing.JTextField studnr;
    private javax.swing.JComboBox<String> studrComboBox;
    private javax.swing.JButton updateModuleButton;
    // End of variables declaration//GEN-END:variables
}
